jenkinsdata:
 build: jenkins-data
jenkinsmaster:
 build: jenkins-master
 volumes_from:
  - jenkinsdata
 ports:
  - "50000:50000"
jenkinsnginx:
 build: jenkins-nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkins-master
jslavejava8:
 build: jslave-java8
jslavenode:
 build: jslave-nodejs445
 volumes_from:
  - jslavedata
jslavedata:
 build: jenkins-slavedata

