version: '2'
services:
  jenkinsdata:
    build: jenkins-data
    depends_on:
      - jenkinsmaster
  jenkinsmaster:
    build: jenkins-master
    depends_on:
      - jenkinssuper
  jenkinsnginx:
    build: jenkins-nginx
    environment:
      - "TZ=America/Denver"
  jslavejava8:
    build: jslave-java8
  jslavenode:
    build: 
      context: jslave-nodejs445
      args:
        DOCKER_GID: ${DOCKERGID}
    depends_on:
      - jslavejava8
  jslavedata:
    build: 
      context: jslave-data
    depends_on:
      - jslavenode
  sshcoderepo:
    build: 
      context: ssh-coderepo
    depends_on:
      - jslavejava8
  sshdata:
    build: 
      context: ssh-data
      args:
        BUILDFARM_HOST: ${BUILDFARM_HOSTNAME}
    depends_on:
      - sshcoderepo
  jenkinssuper:
     build:
       context: jenkins-super


